from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    DateTime
)

from datetime import datetime

from sqlalchemy.orm import declarative_base


# ============================================================
# SQLAlchemy Base
# ============================================================

Base = declarative_base()


# ============================================================
# VISITOR COUNTER
# ============================================================

class Visitor(Base):

    __tablename__ = "visitors"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    # --------------------------------------------------------
    # TOTAL UNIQUE VISITOR COUNT
    # --------------------------------------------------------
    #
    # Example:
    #
    # 42 = existing baseline
    # 43 = one new unique browser
    # 44 = another new unique browser
    #
    # Returning visitors do NOT increase this value.
    # --------------------------------------------------------

    count = Column(
        Integer,
        nullable=False,
        default=0
    )


# ============================================================
# UNIQUE VISITOR ANALYTICS
# ============================================================

class VisitorLog(Base):

    __tablename__ = "visitor_logs"

    # --------------------------------------------------------
    # PRIMARY KEY
    # --------------------------------------------------------

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    # --------------------------------------------------------
    # UNIQUE DEVICE / BROWSER ID
    # --------------------------------------------------------
    #
    # Generated by the frontend using:
    #
    # crypto.randomUUID()
    #
    # Example:
    #
    # 550e8400-e29b-41d4-a716-446655440000
    #
    # UNIQUE means one device_id can only have one
    # VisitorLog record.
    # --------------------------------------------------------

    device_id = Column(
        String(255),
        unique=True,
        nullable=False,
        index=True
    )

    # --------------------------------------------------------
    # FIRST TIME THIS DEVICE WAS SEEN
    # --------------------------------------------------------

    first_visit = Column(
        DateTime,
        nullable=False,
        default=datetime.utcnow
    )

    # --------------------------------------------------------
    # MOST RECENT TIME THIS DEVICE WAS SEEN
    # --------------------------------------------------------

    last_visit = Column(
        DateTime,
        nullable=False,
        default=datetime.utcnow
    )

    # --------------------------------------------------------
    # NUMBER OF VISITS FROM THIS DEVICE
    # --------------------------------------------------------
    #
    # First visit:
    #     1
    #
    # Second visit:
    #     2
    #
    # Third visit:
    #     3
    #
    # This DOES NOT increase Visitor.count.
    # --------------------------------------------------------

    visit_count = Column(
        Integer,
        nullable=False,
        default=1
    )

    # --------------------------------------------------------
    # IP ADDRESS
    # --------------------------------------------------------

    ip_address = Column(
        String(100),
        nullable=True
    )

    # --------------------------------------------------------
    # BROWSER USER AGENT
    # --------------------------------------------------------

    browser = Column(
        String(255),
        nullable=True
    )

    # --------------------------------------------------------
    # OPERATING SYSTEM
    # --------------------------------------------------------

    operating_system = Column(
        String(255),
        nullable=True
    )

    # --------------------------------------------------------
    # OPTIONAL LOCATION
    # --------------------------------------------------------

    country = Column(
        String(255),
        nullable=True
    )

    city = Column(
        String(255),
        nullable=True
    )

    # --------------------------------------------------------
    # ORIGINAL VISIT TIMESTAMP
    # --------------------------------------------------------
    #
    # Kept because your existing backend/frontend may already
    # use visited_at.
    #
    # For a new visitor this is effectively the same as
    # first_visit.
    # --------------------------------------------------------

    visited_at = Column(
        DateTime,
        nullable=False,
        default=datetime.utcnow
    )


# ============================================================
# CONTACT MESSAGES
# ============================================================

class ContactMessage(Base):

    __tablename__ = "contact_messages"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    name = Column(
        String(100),
        nullable=False
    )

    email = Column(
        String(255),
        nullable=False
    )

    message = Column(
        Text,
        nullable=False
    )

    created_at = Column(
        DateTime,
        nullable=False,
        default=datetime.utcnow
    )
